pipeline {
  agent any

  stages {

    stage('checkout') {
      steps {
        git url: "https://github.com/samar-raghav1/Stremify.git", branch: "main"
      }
    }

    stage('build') {
      steps {
        echo 'building docker for client'
        sh 'docker build -t stremify-client ./client'
        echo 'docker image build'
      }
    }

    stage('push to docker hub') {
      steps {
        echo 'pushing image to docker hub'

        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          echo '$DOCKER_USER'

          sh """
              echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            """

          sh 'docker tag stremify-client:latest ${DOCKER_USER}/stremify-client:latest'

          sh 'docker push ${DOCKER_USER}/stremify-client:latest'

          echo 'Image Pushed'
        }
      }
    }

    stage('deploy') {
      steps {
        echo 'deploying image'
    
        sh 'ls -la'
        sh 'cd client'
        sh 'docker compose -f client/docker-compose.yml down && docker compose -f client/docker-compose.yml up -d --build'
      }
    }

  }
}
